const skillsOptions = [
  { label: "Electrician (बिजली मिस्त्री)", value: "electrician" },
  { label: "Plumber (प्लंबर)", value: "plumber" },
  { label: "Carpenter (बढ़ई)", value: "carpenter" },
  { label: "Mason (राज मिस्त्री)", value: "mason" },
  { label: "Painter (पेंटर)", value: "painter" },
  { label: "Welder (वेल्डर)", value: "welder" },
  { label: "AC Mechanic (एसी मैकेनिक)", value: "ac-mechanic" },
  { label: "Refrigerator Mechanic (फ्रिज मैकेनिक)", value: "refrigerator-mechanic" },
  { label: "Washing Machine Repair (वाशिंग मशीन रिपेयर)", value: "washing-machine-repair" },
  { label: "TV Repair (टीवी रिपेयर)", value: "tv-repair" },
  { label: "Mobile Repair (मोबाइल रिपेयर)", value: "mobile-repair" },
  { label: "Computer Repair (कंप्यूटर रिपेयर)", value: "computer-repair" },
  { label: "House Cleaning (घर की सफाई)", value: "house-cleaning" },
  { label: "Bathroom Cleaning (बाथरूम सफाई)", value: "bathroom-cleaning" },
  { label: "Kitchen Cleaning (रसोई सफाई)", value: "kitchen-cleaning" },
  { label: "Sofa Cleaning (सोफा सफाई)", value: "sofa-cleaning" },
  { label: "Water Tank Cleaning (पानी टैंक सफाई)", value: "water-tank-cleaning" },
  { label: "Pest Control (कीट नियंत्रण)", value: "pest-control" },
  { label: "Gardener / Mali (माली)", value: "gardener" },
  { label: "Cook (रसोइया)", value: "cook" },
  { label: "Driver (चालक)", value: "driver" },
  { label: "Watchman / Security (चौकीदार)", value: "watchman" },
  { label: "Housekeeping (हाउसकीपिंग)", value: "housekeeping" },
  { label: "Construction Labour (निर्माण मजदूर)", value: "construction-labour" },
  { label: "Furniture Assembling (फर्नीचर असेंबलिंग)", value: "furniture-assembling" },
  { label: "Roof Waterproofing (छत वॉटरप्रूफिंग)", value: "roof-waterproofing" },
  { label: "Tile Fitting (टाइल फिटिंग)", value: "tile-fitting" },
  { label: "Marble Polish (मार्बल पॉलिश)", value: "marble-polish" },
  { label: "POP / False Ceiling (पीओपी फॉल्स सीलिंग)", value: "pop-false-ceiling" },
  { label: "CCTV Installation (सीसीटीवी इंस्टॉलेशन)", value: "cctv-installation" },
  { label: "Ceiling Fan Installation (फैन इंस्टॉलेशन)", value: "fan-installation" },
  { label: "Inverter & Battery Setup (इन्वर्टर सेटअप)", value: "inverter-setup" },
  { label: "Aluminium Fabrication (एल्यूमीनियम फैब्रिकेशन)", value: "aluminium-fabrication" },
  { label: "Glass Work (ग्लास वर्क)", value: "glass-work" },
  { label: "Iron Grills & Gates (लोहे की जाली और गेट)", value: "iron-grills-gates" },
  { label: "Scaffolding (स्कैफोल्डिंग)", value: "scaffolding" },
  { label: "Elevator Maintenance (लिफ्ट मेंटेनेंस)", value: "elevator-maintenance" },
  { label: "Landscaping (लैंडस्केपिंग)", value: "landscaping" },
  { label: "Septic Tank Cleaning (सेप्टिक टैंक सफाई)", value: "septic-tank-cleaning" },
  { label: "General Labour (सामान्य मजदूर)", value: "general-labour" },
  { label: "Other (अन्य)", value: "other" }
];
export default skillsOptions;
