const skillsOptions = [
  { label: "Electrician", value: "electrician" },
  { label: "Plumber", value: "plumber" },
  { label: "Carpenter", value: "carpenter" },
  { label: "Mason (Civil Work)", value: "mason" },
  { label: "Painter", value: "painter" },
  { label: "Welder", value: "welder" },
  { label: "AC Mechanic", value: "ac-mechanic" },
  { label: "Refrigerator Mechanic", value: "refrigerator-mechanic" },
  { label: "Washing Machine Repair", value: "washing-machine-repair" },
  { label: "TV Repair", value: "tv-repair" },
  { label: "Mobile Repair", value: "mobile-repair" },
  { label: "Computer Repair", value: "computer-repair" },
  { label: "House Cleaning", value: "house-cleaning" },
  { label: "Bathroom Cleaning", value: "bathroom-cleaning" },
  { label: "Kitchen Cleaning", value: "kitchen-cleaning" },
  { label: "Sofa Cleaning", value: "sofa-cleaning" },
  { label: "Water Tank Cleaning", value: "water-tank-cleaning" },
  { label: "Pest Control", value: "pest-control" },
  { label: "Gardener / Mali", value: "gardener" },
  { label: "Cook", value: "cook" },
  { label: "Driver", value: "driver" },
  { label: "Watchman / Security", value: "watchman" },
  { label: "Housekeeping", value: "housekeeping" },
  { label: "Construction Labour", value: "construction-labour" },
  { label: "Furniture Assembling", value: "furniture-assembling" },
  { label: "Roof Waterproofing", value: "roof-waterproofing" },
  { label: "Tile Fitting", value: "tile-fitting" },
  { label: "Marble Polish", value: "marble-polish" },
  { label: "POP / False Ceiling", value: "pop-false-ceiling" },
  { label: "CCTV Installation", value: "cctv-installation" },
  { label: "Ceiling Fan Installation", value: "fan-installation" },
  { label: "Inverter & Battery Setup", value: "inverter-setup" },
  { label: "Aluminium Fabrication", value: "aluminium-fabrication" },
  { label: "Glass Work", value: "glass-work" },
  { label: "Iron Grills & Gates", value: "iron-grills-gates" },
  { label: "Scaffolding", value: "scaffolding" },
  { label: "Elevator Maintenance", value: "elevator-maintenance" },
  { label: "Landscaping", value: "landscaping" },
  { label: "Septic Tank Cleaning", value: "septic-tank-cleaning" },
  { label: "General Labour", value: "general-labour" },
  { label: "Other", value: "other" }
];
export default skillsOptions;
